In [ ]:
#   Day 01

In [1]:
#关于python的基本数据类型
age = 22
salary = 4000
luky_num = 7.9
name = 'Milo_zhang'
is_regular_employee = False
nothing = None

# 容器类型
# list(列表)——有序的集合，用[]
fruits = ["苹果","香蕉","草莓"]
print(fruits[0])
fruits.append("西瓜")
print(len(fruits))


苹果
4


In [9]:
# dict （字典）——键值对 ，用{}
person = {"name": "Milo","age":22,"city":"合肥"}
print(person["name"])
print(person.keys())
print(person.values())
person["job"] = "分析师"

print(person)

Milo
dict_keys(['name', 'age', 'city'])
dict_values(['Milo', 22, '合肥'])
{'name': 'Milo', 'age': 22, 'city': '合肥', 'job': '分析师'}


In [12]:
#tuple 元组 ——不可变的列表，用（）
point = (10,20,40,89,20,20)

print(point)

print(point.index(20))

print(point.count(20))

(10, 20, 40, 89, 20, 20)
1
3


In [13]:
# set（集合）—— 无序不重复，用 {}
tags = {"诈骗", "洗钱", "诈骗"}
print(tags)          # {"诈骗", "洗钱"} 自动去重

{'洗钱', '诈骗'}


In [26]:
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
#  Day 02

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


In [14]:
# python 核心语法
# 2.1 条件判断

score = 85

if score >90:
    print("优秀")
elif score >= 80:
    print("良好")
else:
    print("继续加油")

if score >= 80 and score <90:
    print("80~90 之间")

if score <60 or score >95:
    print("特殊区间")
    

良好
80~90 之间


In [15]:
# 2.2 for 循环
fruits = ["苹果","香蕉","橘子"]
for f in fruits:
    print(f"今天吃{f}")

今天吃苹果
今天吃香蕉
今天吃橘子


In [25]:
# range ——生成数字序列
for i in range(5):    #  0，1，2，3，4
    print(i,end=' ')

print()

for i in range(2,6): #  2,3,4,5
    print(i,end='--')

print()

# while 循环 —— 条件满足就一直跑
count = 0
while count < 3:
    print(f"第{count+1}次")
    count += 1         # 别忘了加1，否则死循环

0 1 2 3 4 
2--3--4--5--
第1次
第2次
第3次


In [28]:
#  2.3 函数
# 定义函数
def greet(name):
    """给某人打招呼"""  # 这是文档字符串，解释函数用途
    return f"你好,{name}!"

# 调用函数
msg = greet("小明")
print(msg)

# 多个参数
def add(a,b):
    return a + b

result = add(3,5)  #result = 8

#默认参数
def say_hello(name,title="同学"):
    print(f"{name}{title},你好！")

say_hello('小明')
say_hello('小明','老师')


你好,小明!
小明同学,你好！
小明老师,你好！


In [33]:
### 2.4 列表推导式
# 传统写法
squares = []
for i in range(10):
    squares.append(i*i)
print()

# 列表推导式 —— 一行搞定
squares = [i*i for i in range(10)]
print(squares)
print()

# 加条件 
even_squares = [i * i for i in range(10) if i % 2 == 0]
print(even_squares)


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

[0, 4, 16, 36, 64]


In [34]:
# 2.5异常处理
# 防止程序崩溃
try:
    num = int(input("请输入一个数字："))
    result = 10 / num
    print(f"10 / {num} = {result}")
except ValueError:
    print("你输入的不是数字！")
except ZeroDivisionError:
    print("不能除以0！")
finally:
    print("不管怎么样都会执行这一段")

请输入一个数字： 4


10 / 4 = 2.5
不管怎么样都会执行这一段


In [35]:
# 2.6 练习

print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


In [38]:
# 练习1：写一个函数 is_even(n)，判断n是否为偶数

def is_even(n):
    if n % 2 == 0:
        print(f"你输入的数字 {n}是偶数 ！")
    else:
        print(f"你输入的数字 {n} 不是偶数")

is_even(9)
is_even(12)

你输入的数字 9 不是偶数
你输入的数字 12是偶数 ！


In [39]:
# 练习2：用列表推导式，生成1-20中能被3整除的数的平方

result = [i*i for i in range(1,21) if i % 3 == 0]
print(result)

[9, 36, 81, 144, 225, 324]


In [43]:
# 练习3：写一个函数，接收一个数字列表，返回最大值和最小值

def find_max_min(num):
    return max(num),min(num)

print(find_max_min([9,21,34,65,34,90,21,7]))

(90, 7)


In [ ]:
# Python 热身
print("~~~~~~~~~~~~~~Day01-Day02~~~~~~~~~~~~~~~~")

In [52]:
# ⚡ 练习1：创建一个字典，包含你的姓名、年龄、城市、职业
# 然后打印 '我是XXX，今年XX岁，在XX做XX工作'

dict_ID = {"name":"Milo","Age":22,"City":"HF","Job":"数据分析"}

print(f"我是{dict_ID['name']},今年已经{dict_ID['Age']}岁,我现在在{dict_ID['City']}工作，职业是{dict_ID['Job']}")

我是Milo,今年已经22岁,我现在在HF工作，职业是数据分析


In [58]:
# ⚡ 练习2：写一个函数，输入一个数字列表，返回所有偶数的平方

def return_suqaresofD(num):
    nums = []
    for i in num:
        if i % 2 == 0:
            nums.append(i*i)
    print(nums)
return_suqaresofD([1,2,3,4,5,6,7,8,9])

[4, 16, 36, 64]


In [61]:
# ⚡ 练习3：用列表推导式写上面的函数（一行搞定）
def test(nums):
    return [n*n for n in nums if n % 2 ==0 ]

print(test([1,2,3,4,5,6,7,8,9]))


[4, 16, 36, 64]


In [73]:
# ⚡ 练习4：写一个函数，接收一个字符串列表，返回长度大于3的字符串

def receive_String(strings):
    return [s for s in strings if len(s) > 3]

test = ["1dadac","张行","涨工资","我是糕手"]
print(receive_String(test))

['1dadac', '我是糕手']


In [75]:
print("~~~~~~~~~~~~~~~~~~~~~~~~~~Day03~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

~~~~~~~~~~~~~~~~~~~~~~~~~~Day03~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


In [2]:
# 关于numpy 基础

## 3.1 什么是numpy ？
    # 他是Python 做数值计算的核心库。其核心是 ndarray(N维数组)
#为什么要用它？
# 比 Python 普通 list 快 50 倍（底层用 C 写的）
#支持矩阵运算、广播运算
#是 Pandas、scikit-learn、PyTorch 的基础

In [8]:
import numpy as np  #惯例 导入为np

#创建数组
arr1 = np.array([1,2,3,4,5])  # 一维数组
arr2 = np.array([[1,2],[3,4]]) #二维数组

print(arr1)
print(arr2)

print("~~~~~~~~~~~~~~~~~~~~~~~")

# 常见创建方式
zeros = np.zeros((3,4))  #三行四列的全0矩阵
print(zeros)
print()

ones = np.ones((2,3))   #两行三列的全1矩阵
print(ones)
print()

range_arr = np.arange(10)  #[0,1,2,...,9] 类似range()
print(range_arr)
print()

lin_arr = np.linspace(0,1,5)  #等间隔，五份
print(lin_arr)

[1 2 3 4 5]
[[1 2]
 [3 4]]
~~~~~~~~~~~~~~~~~~~~~~~
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[0 1 2 3 4 5 6 7 8 9]

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# 查看数组属性
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)   # 两行三列

print(arr.ndim)   # 维度数

print(arr.size)  #元素数，总共多少个元素

print(arr.dtype)  #数据类型





